import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth';
 
import 'bootstrap/dist/css/bootstrap.css';
import SessionProvider  from '../app/components/SessionProvider';
import NavMenu from './components/NavMenu';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
            {/* <main className="d-flex flex-column justify-content-center align-items-center"> */}
                {/* <NavMenu /> */}
            {children}
            {/* </main> */}
        </SessionProvider>
        </body>
    </html>
  )
}
